"""
Pydantic Schemas for Request/Response Validation.

This module provides:
- Pydantic models for API request validation
- Pydantic models for API response serialization
- TypedDict for in-memory database structure (deprecated, kept for reference)

Pydantic models are used by FastAPI to:
1. Validate incoming request data automatically
2. Serialize response data to JSON
3. Generate OpenAPI documentation (Swagger UI)
"""

from typing import TypedDict

from pydantic import BaseModel


# =============================================================================
# Blog Response Schema (Full Details)
# =============================================================================
class BlogSchema(BaseModel):
    """
    Pydantic schema for complete Blog response.

    This schema maps directly to the SQLAlchemy Blog model and includes
    all fields. It's used when you need the full blog data including
    the content field.

    Attributes:
        id: Unique identifier for the blog post
        title: The title of the blog post
        description: A brief summary/description of the blog post
        content: The full content/body of the blog post

    Config:
        from_attributes: Set to True to allow creating instances from
                         SQLAlchemy model objects using their attributes.
                         This enables: BlogSchema.model_validate(db_blog)
    """

    id: int
    title: str
    description: str
    content: str

    class Config:
        """Pydantic configuration for BlogSchema."""

        from_attributes = True  # Allows creating from SQLAlchemy model instances


# =============================================================================
# Blog Creation Schema (Request Body)
# =============================================================================
class BlogCreate(BaseModel):
    """
    Pydantic schema for creating a new blog post.

    This schema is used as the request body for POST endpoints.
    It excludes the 'id' field since that's auto-generated by the database.

    Attributes:
        title: The title of the blog post (required)
        description: A brief summary of the blog post (required)
        content: The full content/body of the blog post (required)

    Example request body:
        {
            "title": "My Blog Post",
            "description": "A short description",
            "content": "Full blog content here..."
        }
    """

    title: str
    description: str
    content: str


# =============================================================================
# Blog Wrapper Schema
# =============================================================================
class Blogs(BaseModel):
    """
    Wrapper schema containing a single blog.

    This is a utility schema that wraps a BlogSchema object.
    Useful when you want to return a response with a named 'blog' field.

    Attributes:
        blog: A complete BlogSchema object
    """

    blog: BlogSchema


# =============================================================================
# Single Blog Response Schema
# =============================================================================
class BlogResponse(BaseModel):
    """
    Response schema for a single blog post (simplified).

    This schema is used for endpoints that return a single blog.
    It includes only essential fields for display: id, title, and content.
    The description field is intentionally excluded for brevity.

    Attributes:
        id: Unique identifier for the blog post
        title: The title of the blog post
        content: The full content/body of the blog post

    Config:
        from_attributes: Enables ORM mode for SQLAlchemy compatibility
    """

    id: int
    title: str
    content: str

    class Config:
        """Pydantic configuration for BlogResponse."""

        from_attributes = True


# =============================================================================
# Blog List Response Schema
# =============================================================================
class BlogsResponse(BaseModel):
    """
    Response schema for blog listings (without full content).

    This schema is optimized for list views where you don't need
    the full content of each blog post. It includes only the fields
    needed for displaying a blog preview/card.

    This is useful for:
    - Blog index pages
    - Search results
    - Related posts widgets

    Attributes:
        id: Unique identifier (for linking to full blog)
        title: The title of the blog post
        description: A brief summary for preview

    Config:
        from_attributes: Enables ORM mode for SQLAlchemy compatibility
    """

    id: int
    title: str
    description: str

    class Config:
        """Pydantic configuration for BlogsResponse."""

        from_attributes = True


# =============================================================================
# TypedDict for In-Memory Database (Deprecated)
# =============================================================================
class BlogTable(TypedDict):
    """
    TypedDict representing the blog structure in an in-memory database.

    WARNING: This is deprecated and kept only for reference!
    The application now uses SQLAlchemy with PostgreSQL for persistence.
    See models.py for the current database model.

    This was previously used when the application stored blogs in a
    Python list as an in-memory database (db: list[BlogTable]).

    Attributes:
        blog_id: The unique identifier for the blog
        title: The title of the blog post
        description: A brief summary of the blog post
        content: The full content of the blog post
    """

    blog_id: int
    title: str
    description: str
    content: str
